import 'bootstrap/dist/css/bootstrap.rtl.css';
import '@popperjs/core';

import '../styles/globals.css'
import Head from "next/head";
import Header from "../Components/header";
import Footer from "../Components/footer";


function MyApp({ Component, pageProps }) {

  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"/>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                    crossOrigin="anonymous"></script>
        </Head>


        <Header></Header>
        <Component {...pageProps} />
        <Footer></Footer>


      </div>
      )

}

export default MyApp
